Eagerly walk over dot args too.
Maybe these maps need to be evaluatued eagerly because the evaluation
context has gone by the time they are evaluated lazily.  For instance,
without this commit, the following form fails with "CompilerException
java.lang.RuntimeException: Unable to resolve symbol: rename in this
context":

    (macroexpand-all
    '(defn refer
      []
        (let [rename {} sym 1]
          (. *ns* (refer (or (rename sym) sym))))))